//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportifMan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public int ID { get; set; }
        public int idcom { get; set; }
        public string Nom { get; set; }
        public Nullable<System.DateTime> DateCom { get; set; }
    
        public virtual TypeCompetition TypeCompetition { get; set; }
    }
}
