//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportifMan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Critere_sante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Critere_sante()
        {
            this.Santeathletes = new HashSet<Santeathlete>();
        }
    
        public int ID { get; set; }
        public string Nom_indice { get; set; }
        public Nullable<int> Valeur_min { get; set; }
        public Nullable<int> Valeur_max { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Santeathlete> Santeathletes { get; set; }
    }
}
