//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportifMan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Santeathlete
    {
        public int ID { get; set; }
        public Nullable<int> Valeur { get; set; }
        public Nullable<int> Date_exam { get; set; }
        public Nullable<int> Critere_santeID { get; set; }
        public Nullable<int> AthleteID { get; set; }
    
        public virtual Athlete Athlete { get; set; }
        public virtual Critere_sante Critere_sante { get; set; }
    }
}
